import 'tailwindcss'
import './globals.css'
import type { Metadata } from 'next'
import { Podkova, Sora } from 'next/font/google'
import Navbar from '../components/views/Navbar'
import Wrapper from '../components/shared/Wrapper'

const inter = Sora({ subsets: ['latin'] })
weight : ["400,500,600,700,800,900"]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        <Navbar></Navbar>
        {children}
        </Wrapper>
        </body>
    </html>
  )
}
